### Enable IAM SAML for the default organization and add a signing certificate

resource "scaleway_iam_saml" "test" {
}

resource "scaleway_iam_saml_certificate" "main" {
  saml_id = scaleway_iam_saml.test.id
  type    = "signing"
  content = "<signing certificate generated by your Identity Provider>"
}
