# Configuration for markdownlint
# https://github.com/DavidAnson/markdownlint#configuration

default: true
MD007:
  indent: 4

# Disabled Rules
# https://github.com/DavidAnson/markdownlint/blob/master/doc/Rules.md

MD001: false
MD003: false
MD004: false
MD006: false
MD010: false
MD012: false
MD013: false
MD022: false
MD037: false
MD038: false
MD041: false
MD060: false
