## Example Dynamic

resource "scaleway_vpc_private_network" "main" {
}

resource "scaleway_instance_server" "main" {
  image = "ubuntu_jammy"
  type  = "DEV1-S"
  zone  = "fr-par-1"
}

resource "scaleway_instance_private_nic" "main" {
  server_id          = scaleway_instance_server.main.id
  private_network_id = scaleway_vpc_private_network.main.id
}

resource "scaleway_vpc_public_gateway_ip" "main" {
}

resource "scaleway_vpc_public_gateway_dhcp" "main" {
  subnet = "192.168.1.0/24"
}

resource "scaleway_vpc_public_gateway" "main" {
  name  = "foobar"
  type  = "VPC-GW-S"
  ip_id = scaleway_vpc_public_gateway_ip.main.id
}

resource "scaleway_vpc_gateway_network" "main" {
  gateway_id         = scaleway_vpc_public_gateway.main.id
  private_network_id = scaleway_vpc_private_network.main.id
  dhcp_id            = scaleway_vpc_public_gateway_dhcp.main.id
  cleanup_dhcp       = true
  enable_masquerade  = true
}

## Retrieve the dynamic entries generated by mac address & gateway network
data "scaleway_vpc_public_gateway_dhcp_reservation" "by_mac_address_and_gw_network" {
  mac_address        = scaleway_instance_private_nic.main.mac_address
  gateway_network_id = scaleway_vpc_gateway_network.main.id
}
