// Code generated by MockGen. DO NOT EDIT.
// Source: scaleway/rdb_interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	rdb "github.com/scaleway/scaleway-sdk-go/api/rdb/v1"
	scw "github.com/scaleway/scaleway-sdk-go/scw"
)

// MockRdbAPIInterface is a mock of RdbAPIInterface interface.
type MockRdbAPIInterface struct {
	ctrl     *gomock.Controller
	recorder *MockRdbAPIInterfaceMockRecorder
}

// MockRdbAPIInterfaceMockRecorder is the mock recorder for MockRdbAPIInterface.
type MockRdbAPIInterfaceMockRecorder struct {
	mock *MockRdbAPIInterface
}

// NewMockRdbAPIInterface creates a new mock instance.
func NewMockRdbAPIInterface(ctrl *gomock.Controller) *MockRdbAPIInterface {
	mock := &MockRdbAPIInterface{ctrl: ctrl}
	mock.recorder = &MockRdbAPIInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRdbAPIInterface) EXPECT() *MockRdbAPIInterfaceMockRecorder {
	return m.recorder
}

// AddInstanceACLRules mocks base method.
func (m *MockRdbAPIInterface) AddInstanceACLRules(req *rdb.AddInstanceACLRulesRequest, opts ...scw.RequestOption) (*rdb.AddInstanceACLRulesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddInstanceACLRules", varargs...)
	ret0, _ := ret[0].(*rdb.AddInstanceACLRulesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddInstanceACLRules indicates an expected call of AddInstanceACLRules.
func (mr *MockRdbAPIInterfaceMockRecorder) AddInstanceACLRules(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInstanceACLRules", reflect.TypeOf((*MockRdbAPIInterface)(nil).AddInstanceACLRules), varargs...)
}

// AddInstanceSettings mocks base method.
func (m *MockRdbAPIInterface) AddInstanceSettings(req *rdb.AddInstanceSettingsRequest, opts ...scw.RequestOption) (*rdb.AddInstanceSettingsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AddInstanceSettings", varargs...)
	ret0, _ := ret[0].(*rdb.AddInstanceSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddInstanceSettings indicates an expected call of AddInstanceSettings.
func (mr *MockRdbAPIInterfaceMockRecorder) AddInstanceSettings(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInstanceSettings", reflect.TypeOf((*MockRdbAPIInterface)(nil).AddInstanceSettings), varargs...)
}

// CloneInstance mocks base method.
func (m *MockRdbAPIInterface) CloneInstance(req *rdb.CloneInstanceRequest, opts ...scw.RequestOption) (*rdb.Instance, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CloneInstance", varargs...)
	ret0, _ := ret[0].(*rdb.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloneInstance indicates an expected call of CloneInstance.
func (mr *MockRdbAPIInterfaceMockRecorder) CloneInstance(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneInstance", reflect.TypeOf((*MockRdbAPIInterface)(nil).CloneInstance), varargs...)
}

// CreateDatabase mocks base method.
func (m *MockRdbAPIInterface) CreateDatabase(req *rdb.CreateDatabaseRequest, opts ...scw.RequestOption) (*rdb.Database, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateDatabase", varargs...)
	ret0, _ := ret[0].(*rdb.Database)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDatabase indicates an expected call of CreateDatabase.
func (mr *MockRdbAPIInterfaceMockRecorder) CreateDatabase(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDatabase", reflect.TypeOf((*MockRdbAPIInterface)(nil).CreateDatabase), varargs...)
}

// CreateDatabaseBackup mocks base method.
func (m *MockRdbAPIInterface) CreateDatabaseBackup(req *rdb.CreateDatabaseBackupRequest, opts ...scw.RequestOption) (*rdb.DatabaseBackup, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateDatabaseBackup", varargs...)
	ret0, _ := ret[0].(*rdb.DatabaseBackup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateDatabaseBackup indicates an expected call of CreateDatabaseBackup.
func (mr *MockRdbAPIInterfaceMockRecorder) CreateDatabaseBackup(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDatabaseBackup", reflect.TypeOf((*MockRdbAPIInterface)(nil).CreateDatabaseBackup), varargs...)
}

// CreateInstance mocks base method.
func (m *MockRdbAPIInterface) CreateInstance(req *rdb.CreateInstanceRequest, opts ...scw.RequestOption) (*rdb.Instance, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateInstance", varargs...)
	ret0, _ := ret[0].(*rdb.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstance indicates an expected call of CreateInstance.
func (mr *MockRdbAPIInterfaceMockRecorder) CreateInstance(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstance", reflect.TypeOf((*MockRdbAPIInterface)(nil).CreateInstance), varargs...)
}

// CreateInstanceFromSnapshot mocks base method.
func (m *MockRdbAPIInterface) CreateInstanceFromSnapshot(req *rdb.CreateInstanceFromSnapshotRequest, opts ...scw.RequestOption) (*rdb.Instance, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateInstanceFromSnapshot", varargs...)
	ret0, _ := ret[0].(*rdb.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInstanceFromSnapshot indicates an expected call of CreateInstanceFromSnapshot.
func (mr *MockRdbAPIInterfaceMockRecorder) CreateInstanceFromSnapshot(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInstanceFromSnapshot", reflect.TypeOf((*MockRdbAPIInterface)(nil).CreateInstanceFromSnapshot), varargs...)
}

// CreateSnapshot mocks base method.
func (m *MockRdbAPIInterface) CreateSnapshot(req *rdb.CreateSnapshotRequest, opts ...scw.RequestOption) (*rdb.Snapshot, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateSnapshot", varargs...)
	ret0, _ := ret[0].(*rdb.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSnapshot indicates an expected call of CreateSnapshot.
func (mr *MockRdbAPIInterfaceMockRecorder) CreateSnapshot(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSnapshot", reflect.TypeOf((*MockRdbAPIInterface)(nil).CreateSnapshot), varargs...)
}

// CreateUser mocks base method.
func (m *MockRdbAPIInterface) CreateUser(req *rdb.CreateUserRequest, opts ...scw.RequestOption) (*rdb.User, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateUser", varargs...)
	ret0, _ := ret[0].(*rdb.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRdbAPIInterfaceMockRecorder) CreateUser(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRdbAPIInterface)(nil).CreateUser), varargs...)
}

// DeleteDatabase mocks base method.
func (m *MockRdbAPIInterface) DeleteDatabase(req *rdb.DeleteDatabaseRequest, opts ...scw.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteDatabase", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteDatabase indicates an expected call of DeleteDatabase.
func (mr *MockRdbAPIInterfaceMockRecorder) DeleteDatabase(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDatabase", reflect.TypeOf((*MockRdbAPIInterface)(nil).DeleteDatabase), varargs...)
}

// DeleteDatabaseBackup mocks base method.
func (m *MockRdbAPIInterface) DeleteDatabaseBackup(req *rdb.DeleteDatabaseBackupRequest, opts ...scw.RequestOption) (*rdb.DatabaseBackup, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteDatabaseBackup", varargs...)
	ret0, _ := ret[0].(*rdb.DatabaseBackup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteDatabaseBackup indicates an expected call of DeleteDatabaseBackup.
func (mr *MockRdbAPIInterfaceMockRecorder) DeleteDatabaseBackup(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteDatabaseBackup", reflect.TypeOf((*MockRdbAPIInterface)(nil).DeleteDatabaseBackup), varargs...)
}

// DeleteInstance mocks base method.
func (m *MockRdbAPIInterface) DeleteInstance(req *rdb.DeleteInstanceRequest, opts ...scw.RequestOption) (*rdb.Instance, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteInstance", varargs...)
	ret0, _ := ret[0].(*rdb.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteInstance indicates an expected call of DeleteInstance.
func (mr *MockRdbAPIInterfaceMockRecorder) DeleteInstance(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstance", reflect.TypeOf((*MockRdbAPIInterface)(nil).DeleteInstance), varargs...)
}

// DeleteInstanceACLRules mocks base method.
func (m *MockRdbAPIInterface) DeleteInstanceACLRules(req *rdb.DeleteInstanceACLRulesRequest, opts ...scw.RequestOption) (*rdb.DeleteInstanceACLRulesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteInstanceACLRules", varargs...)
	ret0, _ := ret[0].(*rdb.DeleteInstanceACLRulesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteInstanceACLRules indicates an expected call of DeleteInstanceACLRules.
func (mr *MockRdbAPIInterfaceMockRecorder) DeleteInstanceACLRules(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstanceACLRules", reflect.TypeOf((*MockRdbAPIInterface)(nil).DeleteInstanceACLRules), varargs...)
}

// DeleteInstanceSettings mocks base method.
func (m *MockRdbAPIInterface) DeleteInstanceSettings(req *rdb.DeleteInstanceSettingsRequest, opts ...scw.RequestOption) (*rdb.DeleteInstanceSettingsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteInstanceSettings", varargs...)
	ret0, _ := ret[0].(*rdb.DeleteInstanceSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteInstanceSettings indicates an expected call of DeleteInstanceSettings.
func (mr *MockRdbAPIInterfaceMockRecorder) DeleteInstanceSettings(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInstanceSettings", reflect.TypeOf((*MockRdbAPIInterface)(nil).DeleteInstanceSettings), varargs...)
}

// DeleteSnapshot mocks base method.
func (m *MockRdbAPIInterface) DeleteSnapshot(req *rdb.DeleteSnapshotRequest, opts ...scw.RequestOption) (*rdb.Snapshot, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteSnapshot", varargs...)
	ret0, _ := ret[0].(*rdb.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteSnapshot indicates an expected call of DeleteSnapshot.
func (mr *MockRdbAPIInterfaceMockRecorder) DeleteSnapshot(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSnapshot", reflect.TypeOf((*MockRdbAPIInterface)(nil).DeleteSnapshot), varargs...)
}

// DeleteUser mocks base method.
func (m *MockRdbAPIInterface) DeleteUser(req *rdb.DeleteUserRequest, opts ...scw.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteUser", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteUser indicates an expected call of DeleteUser.
func (mr *MockRdbAPIInterfaceMockRecorder) DeleteUser(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteUser", reflect.TypeOf((*MockRdbAPIInterface)(nil).DeleteUser), varargs...)
}

// ExportDatabaseBackup mocks base method.
func (m *MockRdbAPIInterface) ExportDatabaseBackup(req *rdb.ExportDatabaseBackupRequest, opts ...scw.RequestOption) (*rdb.DatabaseBackup, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ExportDatabaseBackup", varargs...)
	ret0, _ := ret[0].(*rdb.DatabaseBackup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExportDatabaseBackup indicates an expected call of ExportDatabaseBackup.
func (mr *MockRdbAPIInterfaceMockRecorder) ExportDatabaseBackup(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExportDatabaseBackup", reflect.TypeOf((*MockRdbAPIInterface)(nil).ExportDatabaseBackup), varargs...)
}

// GetDatabaseBackup mocks base method.
func (m *MockRdbAPIInterface) GetDatabaseBackup(req *rdb.GetDatabaseBackupRequest, opts ...scw.RequestOption) (*rdb.DatabaseBackup, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetDatabaseBackup", varargs...)
	ret0, _ := ret[0].(*rdb.DatabaseBackup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDatabaseBackup indicates an expected call of GetDatabaseBackup.
func (mr *MockRdbAPIInterfaceMockRecorder) GetDatabaseBackup(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDatabaseBackup", reflect.TypeOf((*MockRdbAPIInterface)(nil).GetDatabaseBackup), varargs...)
}

// GetInstance mocks base method.
func (m *MockRdbAPIInterface) GetInstance(req *rdb.GetInstanceRequest, opts ...scw.RequestOption) (*rdb.Instance, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInstance", varargs...)
	ret0, _ := ret[0].(*rdb.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstance indicates an expected call of GetInstance.
func (mr *MockRdbAPIInterfaceMockRecorder) GetInstance(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstance", reflect.TypeOf((*MockRdbAPIInterface)(nil).GetInstance), varargs...)
}

// GetInstanceCertificate mocks base method.
func (m *MockRdbAPIInterface) GetInstanceCertificate(req *rdb.GetInstanceCertificateRequest, opts ...scw.RequestOption) (*scw.File, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInstanceCertificate", varargs...)
	ret0, _ := ret[0].(*scw.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstanceCertificate indicates an expected call of GetInstanceCertificate.
func (mr *MockRdbAPIInterfaceMockRecorder) GetInstanceCertificate(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceCertificate", reflect.TypeOf((*MockRdbAPIInterface)(nil).GetInstanceCertificate), varargs...)
}

// GetInstanceLog mocks base method.
func (m *MockRdbAPIInterface) GetInstanceLog(req *rdb.GetInstanceLogRequest, opts ...scw.RequestOption) (*rdb.InstanceLog, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInstanceLog", varargs...)
	ret0, _ := ret[0].(*rdb.InstanceLog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstanceLog indicates an expected call of GetInstanceLog.
func (mr *MockRdbAPIInterfaceMockRecorder) GetInstanceLog(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceLog", reflect.TypeOf((*MockRdbAPIInterface)(nil).GetInstanceLog), varargs...)
}

// GetInstanceMetrics mocks base method.
func (m *MockRdbAPIInterface) GetInstanceMetrics(req *rdb.GetInstanceMetricsRequest, opts ...scw.RequestOption) (*rdb.InstanceMetrics, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetInstanceMetrics", varargs...)
	ret0, _ := ret[0].(*rdb.InstanceMetrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInstanceMetrics indicates an expected call of GetInstanceMetrics.
func (mr *MockRdbAPIInterfaceMockRecorder) GetInstanceMetrics(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInstanceMetrics", reflect.TypeOf((*MockRdbAPIInterface)(nil).GetInstanceMetrics), varargs...)
}

// GetServiceInfo mocks base method.
func (m *MockRdbAPIInterface) GetServiceInfo(req *rdb.GetServiceInfoRequest, opts ...scw.RequestOption) (*scw.ServiceInfo, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetServiceInfo", varargs...)
	ret0, _ := ret[0].(*scw.ServiceInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetServiceInfo indicates an expected call of GetServiceInfo.
func (mr *MockRdbAPIInterfaceMockRecorder) GetServiceInfo(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetServiceInfo", reflect.TypeOf((*MockRdbAPIInterface)(nil).GetServiceInfo), varargs...)
}

// GetSnapshot mocks base method.
func (m *MockRdbAPIInterface) GetSnapshot(req *rdb.GetSnapshotRequest, opts ...scw.RequestOption) (*rdb.Snapshot, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetSnapshot", varargs...)
	ret0, _ := ret[0].(*rdb.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSnapshot indicates an expected call of GetSnapshot.
func (mr *MockRdbAPIInterfaceMockRecorder) GetSnapshot(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSnapshot", reflect.TypeOf((*MockRdbAPIInterface)(nil).GetSnapshot), varargs...)
}

// ListDatabaseBackups mocks base method.
func (m *MockRdbAPIInterface) ListDatabaseBackups(req *rdb.ListDatabaseBackupsRequest, opts ...scw.RequestOption) (*rdb.ListDatabaseBackupsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDatabaseBackups", varargs...)
	ret0, _ := ret[0].(*rdb.ListDatabaseBackupsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDatabaseBackups indicates an expected call of ListDatabaseBackups.
func (mr *MockRdbAPIInterfaceMockRecorder) ListDatabaseBackups(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDatabaseBackups", reflect.TypeOf((*MockRdbAPIInterface)(nil).ListDatabaseBackups), varargs...)
}

// ListDatabaseEngines mocks base method.
func (m *MockRdbAPIInterface) ListDatabaseEngines(req *rdb.ListDatabaseEnginesRequest, opts ...scw.RequestOption) (*rdb.ListDatabaseEnginesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDatabaseEngines", varargs...)
	ret0, _ := ret[0].(*rdb.ListDatabaseEnginesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDatabaseEngines indicates an expected call of ListDatabaseEngines.
func (mr *MockRdbAPIInterfaceMockRecorder) ListDatabaseEngines(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDatabaseEngines", reflect.TypeOf((*MockRdbAPIInterface)(nil).ListDatabaseEngines), varargs...)
}

// ListDatabases mocks base method.
func (m *MockRdbAPIInterface) ListDatabases(req *rdb.ListDatabasesRequest, opts ...scw.RequestOption) (*rdb.ListDatabasesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListDatabases", varargs...)
	ret0, _ := ret[0].(*rdb.ListDatabasesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDatabases indicates an expected call of ListDatabases.
func (mr *MockRdbAPIInterfaceMockRecorder) ListDatabases(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDatabases", reflect.TypeOf((*MockRdbAPIInterface)(nil).ListDatabases), varargs...)
}

// ListInstanceACLRules mocks base method.
func (m *MockRdbAPIInterface) ListInstanceACLRules(req *rdb.ListInstanceACLRulesRequest, opts ...scw.RequestOption) (*rdb.ListInstanceACLRulesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListInstanceACLRules", varargs...)
	ret0, _ := ret[0].(*rdb.ListInstanceACLRulesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstanceACLRules indicates an expected call of ListInstanceACLRules.
func (mr *MockRdbAPIInterfaceMockRecorder) ListInstanceACLRules(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstanceACLRules", reflect.TypeOf((*MockRdbAPIInterface)(nil).ListInstanceACLRules), varargs...)
}

// ListInstanceLogs mocks base method.
func (m *MockRdbAPIInterface) ListInstanceLogs(req *rdb.ListInstanceLogsRequest, opts ...scw.RequestOption) (*rdb.ListInstanceLogsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListInstanceLogs", varargs...)
	ret0, _ := ret[0].(*rdb.ListInstanceLogsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstanceLogs indicates an expected call of ListInstanceLogs.
func (mr *MockRdbAPIInterfaceMockRecorder) ListInstanceLogs(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstanceLogs", reflect.TypeOf((*MockRdbAPIInterface)(nil).ListInstanceLogs), varargs...)
}

// ListInstances mocks base method.
func (m *MockRdbAPIInterface) ListInstances(req *rdb.ListInstancesRequest, opts ...scw.RequestOption) (*rdb.ListInstancesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListInstances", varargs...)
	ret0, _ := ret[0].(*rdb.ListInstancesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInstances indicates an expected call of ListInstances.
func (mr *MockRdbAPIInterfaceMockRecorder) ListInstances(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInstances", reflect.TypeOf((*MockRdbAPIInterface)(nil).ListInstances), varargs...)
}

// ListNodeTypes mocks base method.
func (m *MockRdbAPIInterface) ListNodeTypes(req *rdb.ListNodeTypesRequest, opts ...scw.RequestOption) (*rdb.ListNodeTypesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListNodeTypes", varargs...)
	ret0, _ := ret[0].(*rdb.ListNodeTypesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListNodeTypes indicates an expected call of ListNodeTypes.
func (mr *MockRdbAPIInterfaceMockRecorder) ListNodeTypes(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListNodeTypes", reflect.TypeOf((*MockRdbAPIInterface)(nil).ListNodeTypes), varargs...)
}

// ListPrivileges mocks base method.
func (m *MockRdbAPIInterface) ListPrivileges(req *rdb.ListPrivilegesRequest, opts ...scw.RequestOption) (*rdb.ListPrivilegesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListPrivileges", varargs...)
	ret0, _ := ret[0].(*rdb.ListPrivilegesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPrivileges indicates an expected call of ListPrivileges.
func (mr *MockRdbAPIInterfaceMockRecorder) ListPrivileges(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPrivileges", reflect.TypeOf((*MockRdbAPIInterface)(nil).ListPrivileges), varargs...)
}

// ListSnapshots mocks base method.
func (m *MockRdbAPIInterface) ListSnapshots(req *rdb.ListSnapshotsRequest, opts ...scw.RequestOption) (*rdb.ListSnapshotsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListSnapshots", varargs...)
	ret0, _ := ret[0].(*rdb.ListSnapshotsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSnapshots indicates an expected call of ListSnapshots.
func (mr *MockRdbAPIInterfaceMockRecorder) ListSnapshots(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSnapshots", reflect.TypeOf((*MockRdbAPIInterface)(nil).ListSnapshots), varargs...)
}

// ListUsers mocks base method.
func (m *MockRdbAPIInterface) ListUsers(req *rdb.ListUsersRequest, opts ...scw.RequestOption) (*rdb.ListUsersResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "ListUsers", varargs...)
	ret0, _ := ret[0].(*rdb.ListUsersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListUsers indicates an expected call of ListUsers.
func (mr *MockRdbAPIInterfaceMockRecorder) ListUsers(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListUsers", reflect.TypeOf((*MockRdbAPIInterface)(nil).ListUsers), varargs...)
}

// PrepareInstanceLogs mocks base method.
func (m *MockRdbAPIInterface) PrepareInstanceLogs(req *rdb.PrepareInstanceLogsRequest, opts ...scw.RequestOption) (*rdb.PrepareInstanceLogsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PrepareInstanceLogs", varargs...)
	ret0, _ := ret[0].(*rdb.PrepareInstanceLogsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareInstanceLogs indicates an expected call of PrepareInstanceLogs.
func (mr *MockRdbAPIInterfaceMockRecorder) PrepareInstanceLogs(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareInstanceLogs", reflect.TypeOf((*MockRdbAPIInterface)(nil).PrepareInstanceLogs), varargs...)
}

// RenewInstanceCertificate mocks base method.
func (m *MockRdbAPIInterface) RenewInstanceCertificate(req *rdb.RenewInstanceCertificateRequest, opts ...scw.RequestOption) error {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RenewInstanceCertificate", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// RenewInstanceCertificate indicates an expected call of RenewInstanceCertificate.
func (mr *MockRdbAPIInterfaceMockRecorder) RenewInstanceCertificate(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenewInstanceCertificate", reflect.TypeOf((*MockRdbAPIInterface)(nil).RenewInstanceCertificate), varargs...)
}

// RestoreDatabaseBackup mocks base method.
func (m *MockRdbAPIInterface) RestoreDatabaseBackup(req *rdb.RestoreDatabaseBackupRequest, opts ...scw.RequestOption) (*rdb.DatabaseBackup, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "RestoreDatabaseBackup", varargs...)
	ret0, _ := ret[0].(*rdb.DatabaseBackup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreDatabaseBackup indicates an expected call of RestoreDatabaseBackup.
func (mr *MockRdbAPIInterfaceMockRecorder) RestoreDatabaseBackup(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreDatabaseBackup", reflect.TypeOf((*MockRdbAPIInterface)(nil).RestoreDatabaseBackup), varargs...)
}

// SetInstanceACLRules mocks base method.
func (m *MockRdbAPIInterface) SetInstanceACLRules(req *rdb.SetInstanceACLRulesRequest, opts ...scw.RequestOption) (*rdb.SetInstanceACLRulesResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetInstanceACLRules", varargs...)
	ret0, _ := ret[0].(*rdb.SetInstanceACLRulesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetInstanceACLRules indicates an expected call of SetInstanceACLRules.
func (mr *MockRdbAPIInterfaceMockRecorder) SetInstanceACLRules(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInstanceACLRules", reflect.TypeOf((*MockRdbAPIInterface)(nil).SetInstanceACLRules), varargs...)
}

// SetInstanceSettings mocks base method.
func (m *MockRdbAPIInterface) SetInstanceSettings(req *rdb.SetInstanceSettingsRequest, opts ...scw.RequestOption) (*rdb.SetInstanceSettingsResponse, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetInstanceSettings", varargs...)
	ret0, _ := ret[0].(*rdb.SetInstanceSettingsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetInstanceSettings indicates an expected call of SetInstanceSettings.
func (mr *MockRdbAPIInterfaceMockRecorder) SetInstanceSettings(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInstanceSettings", reflect.TypeOf((*MockRdbAPIInterface)(nil).SetInstanceSettings), varargs...)
}

// SetPrivilege mocks base method.
func (m *MockRdbAPIInterface) SetPrivilege(req *rdb.SetPrivilegeRequest, opts ...scw.RequestOption) (*rdb.Privilege, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SetPrivilege", varargs...)
	ret0, _ := ret[0].(*rdb.Privilege)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetPrivilege indicates an expected call of SetPrivilege.
func (mr *MockRdbAPIInterfaceMockRecorder) SetPrivilege(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPrivilege", reflect.TypeOf((*MockRdbAPIInterface)(nil).SetPrivilege), varargs...)
}

// UpdateDatabaseBackup mocks base method.
func (m *MockRdbAPIInterface) UpdateDatabaseBackup(req *rdb.UpdateDatabaseBackupRequest, opts ...scw.RequestOption) (*rdb.DatabaseBackup, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateDatabaseBackup", varargs...)
	ret0, _ := ret[0].(*rdb.DatabaseBackup)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateDatabaseBackup indicates an expected call of UpdateDatabaseBackup.
func (mr *MockRdbAPIInterfaceMockRecorder) UpdateDatabaseBackup(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDatabaseBackup", reflect.TypeOf((*MockRdbAPIInterface)(nil).UpdateDatabaseBackup), varargs...)
}

// UpdateInstance mocks base method.
func (m *MockRdbAPIInterface) UpdateInstance(req *rdb.UpdateInstanceRequest, opts ...scw.RequestOption) (*rdb.Instance, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateInstance", varargs...)
	ret0, _ := ret[0].(*rdb.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateInstance indicates an expected call of UpdateInstance.
func (mr *MockRdbAPIInterfaceMockRecorder) UpdateInstance(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInstance", reflect.TypeOf((*MockRdbAPIInterface)(nil).UpdateInstance), varargs...)
}

// UpdateSnapshot mocks base method.
func (m *MockRdbAPIInterface) UpdateSnapshot(req *rdb.UpdateSnapshotRequest, opts ...scw.RequestOption) (*rdb.Snapshot, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateSnapshot", varargs...)
	ret0, _ := ret[0].(*rdb.Snapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSnapshot indicates an expected call of UpdateSnapshot.
func (mr *MockRdbAPIInterfaceMockRecorder) UpdateSnapshot(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSnapshot", reflect.TypeOf((*MockRdbAPIInterface)(nil).UpdateSnapshot), varargs...)
}

// UpdateUser mocks base method.
func (m *MockRdbAPIInterface) UpdateUser(req *rdb.UpdateUserRequest, opts ...scw.RequestOption) (*rdb.User, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpdateUser", varargs...)
	ret0, _ := ret[0].(*rdb.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateUser indicates an expected call of UpdateUser.
func (mr *MockRdbAPIInterfaceMockRecorder) UpdateUser(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUser", reflect.TypeOf((*MockRdbAPIInterface)(nil).UpdateUser), varargs...)
}

// UpgradeInstance mocks base method.
func (m *MockRdbAPIInterface) UpgradeInstance(req *rdb.UpgradeInstanceRequest, opts ...scw.RequestOption) (*rdb.Instance, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "UpgradeInstance", varargs...)
	ret0, _ := ret[0].(*rdb.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpgradeInstance indicates an expected call of UpgradeInstance.
func (mr *MockRdbAPIInterfaceMockRecorder) UpgradeInstance(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpgradeInstance", reflect.TypeOf((*MockRdbAPIInterface)(nil).UpgradeInstance), varargs...)
}

// WaitForInstance mocks base method.
func (m *MockRdbAPIInterface) WaitForInstance(req *rdb.WaitForInstanceRequest, opts ...scw.RequestOption) (*rdb.Instance, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{req}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "WaitForInstance", varargs...)
	ret0, _ := ret[0].(*rdb.Instance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// WaitForInstance indicates an expected call of WaitForInstance.
func (mr *MockRdbAPIInterfaceMockRecorder) WaitForInstance(req interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{req}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WaitForInstance", reflect.TypeOf((*MockRdbAPIInterface)(nil).WaitForInstance), varargs...)
}
