name: Build

permissions:
  contents: read

on:
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: "${{ vars.RUNS_ON || 'ubuntu-latest' }}"

    steps:
      # Checkout should always be before setup-go to ensure caching is working
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1

      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable

      - name: Verify go.mod is tidy
        run: |
          go mod tidy
          git diff --exit-code

      - name: Build the provider
        run: go build ./

      - name: Test cross-platform builds with GoReleaser
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94 # v7.2.3
        with:
          version: 2.13.3
          args: release --snapshot --clean --skip sign --skip archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
