name: Code Coverage

on:
  pull_request:
  merge_group:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  coverage:
    runs-on: "${{ vars.RUNS_ON || 'ubuntu-latest' }}"
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 1

      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: stable

      - name: Install Terraform
        uses: hashicorp/setup-terraform@dfe3c3f87815947d99a8997f908cb6525fc44e9e # v4.0.1

      - name: Build binaries
        run: make build

      - name: Verify go.mod is tidy
        run: |
          go mod tidy
          git diff --exit-code

      - name: Run coverage
        run: go tool gotestsum --format github-actions -- -coverprofile=coverage.out -covermode=count ./...

      - name: Convert coverage to Cobertura XML
        run: go tool gocover-cobertura < coverage.out > coverage.xml

      - name: Upload coverage artifact
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage-report-go
          path: coverage.xml

  upload-coverage-go:
    needs: coverage
    if: ${{ !cancelled() && needs.coverage.result == 'success' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository) && github.event_name != 'merge_group' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      code-quality: write
      pull-requests: read
    steps:
      - name: Download coverage artifact
        uses: actions/download-artifact@v8
        with:
          name: coverage-report-go

      - uses: actions/upload-code-coverage@v1
        with:
          file: coverage.xml
          language: Go
          label: code-coverage-agent
