name: Dev Container Check

permissions:
  contents: read

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: "${{ vars.RUNS_ON || 'ubuntu-latest' }}"
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Build and Run Dev Container
        uses: devcontainers/ci@b63b30de439b47a52267f241112c5b453b673db5 # v0.3.1900000449
        with:
          runCmd: go build .
