name: Run terrafmt

permissions:
  contents: read

on:
  pull_request:
  push:
  merge_group:

jobs:
  terrafmt:
    runs-on: ubuntu-latest
    steps:
      # Checkout should always be before setup-go to ensure caching is working
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Run terrafmt on documentation
        run: go tool terrafmt fmt --verbose --check ./docs
